### PR TITLE
Add 79 math glyphs to Roman masters 0 and 2

### PR DESCRIPTION
**Pull request by tspiteri**
I would like to have a few more math glyphs, some of which are listed in #49, and I had a go at drawing them. I'm not a font designer, so I only did glyphs I think are relatively straightforward or are very similar to some other existing glyphs. (For example I also kinda wanted to do U+2205 ∅, but found it too challenging, and {U+2208 ∈, U+2209 ∉, U+220B ∋, U+220C ∌}, but did not have a suitable starting point like I had U+2229 ∩ for U+222A and U+2282 to U+2289.)

I used fontforge and exported to .ufo, then merged the exported output by hand to the original .ufo as fontforge seems to not like the .fea files in the original .ufo. I've done the extralight (master 0) glyphs for the below codepoints, and before going on to black (master 2), I'd like to know if these are of sufficient quality, otherwise I'd be just wasting everybody's time.

U+2204 ∄ notexistential
U+2210 ∐ coproduct
U+222A ∪ union
U+2234 ∴ therefore
U+2235 ∵ because
U+2236 ∶ ratio
U+223C ∼ similar
U+223D ∽ reversedtilde
U+2254 ≔ colonequal
U+2255 ≕ equalcolon
U+2262 ≢ notidentical
U+226A ≪ muchless
U+226B ≫ muchgreater
U+226E ≮ notless
U+226F ≯ notgreater
U+2270 ≰ notlessequal
U+2271 ≱ notgreaterequal
U+2282 ⊂ propersubset
U+2283 ⊃ propersuperset
U+2284 ⊄ notsubset
U+2285 ⊅ notsuperset
U+2286 ⊆ reflexsubset
U+2287 ⊇ reflexsuperset
U+2288 ⊈ notreflexsubset
U+2289 ⊉ notreflexsubset

### CODE REVIEW

**Comment by tspiteri** [comment]
I went ahead and did black variants (master 2) as well. I did the editing mostly in a text editor to maintain the same point order, using fontforge mainly for visual inspection.

**Comment by tspiteri** [comment]
I have a comment about operator alignments. I vertically aligned therefore U+2234, because U+2235, and ratio U+2236 with proportion U+2237 as they seem to be a similar group. However, unlike other operators such as minus and equals, the center of proportion is not (300, 330).

For extra light master 0, proportion is centered at (300, 329), as period is centered at y=(104−12)/2=46, colon is centered at y=46+386/2=239, and proportion is centered at y=239+90=329.

For black master 2, proportion is centered at (300, 333), as period is centered at y=(248−12)/2=118, colon is centered at y=118+310/2=273, and proportion is centered at y=273+60=333.

**Comment by tspiteri** [comment]
Here is a pdf with a table containing all added chars.
[math_chars.pdf](https://github.com/adobe-fonts/source-code-pro/files/2771224/math_chars.pdf)

**Comment by miguelsousa** [comment]
Thanks Trevor, @pauldhunt will have a look at it soon.

**Comment by cata0309** [comment]
I would like these math glyphs too to be added to the font!

**Comment by glanchow** [comment]
Yes, please merge

**Comment by newking5811** [comment]
Life Time

**Comment by newking5811** [comment]
Life Time race

**Comment by pauldhunt** [comment]
I will look at merging this into the project when I pick this back up later this year. Sorry for the long delay.

**Comment by ifeegoo** [comment]
@tspiteri Thank you for you contribution, can you deal with the merge conflicts?

**Comment by tspiteri** [comment]
@ifeegoo I don't think the merge conflicts themselves were an issue to the font developers, but I rebased anyway.

**Comment by pauldhunt** [comment]
@tspiteri i have enlarged the math glyphs for the next release of Source Code, so instead of merging this branch, I will redraw the characters at the new math glyphs size. I am also including the glyphs you listed as too challenging to draw yourself
- U+2205 ∅, emptyset
- U+2208 ∈, element
- U+2209 ∉, notelement
- U+220B ∋, suchthat
- U+220C ∌, notcontains

**Pull request closed without merging**
